# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /mcp-shrimp-task-manager

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Expose MCP stdio transport (required for Docker MCP Gateway)
# The gateway expects stdio transport, not HTTP
ENV DOCKER_MCP_MODE=true
ENV ENABLE_GUI=false
ENV DATA_DIR=/app/ShrimpData

# Create data directory
RUN mkdir -p /app/ShrimpData

# Set the entrypoint to run our MCP server
ENTRYPOINT ["node", "dist/index.js"]

# Default command (can be overridden by the gateway)
CMD []
